import { ConfigHelperType } from "⌨️";

const enableAaveV3Automations = false

export const getFeatures = ({ notProduction }: ConfigHelperType) => ({
  AaveLikeSimpleEarnSafetySwitch: false,
  AaveLikeSimpleEarnSuppressValidation: false,
  AaveV2SafetySwitch: false,
  AaveV2SuppressValidation: false,
  AaveV3ArbitrumBorrow: true,
  AaveV3ArbitrumEarn: false,
  AaveV3EarncbETHeth: false,
  AaveV3EarnrETHeth: false,
  AaveV3History: true,
  AaveV3LambdaSuppressValidation: false,
  AaveV3OptimismBorrow: true,
  AaveV3OptimismEarn: false,
  AaveV3OptimizationArbitrum: enableAaveV3Automations,
  AaveV3OptimizationBase: enableAaveV3Automations,
  AaveV3OptimizationEthereum: enableAaveV3Automations,
  AaveV3OptimizationOptimism: enableAaveV3Automations,
  AaveV3PartialTakeProfitLambdaArbitrum: enableAaveV3Automations,
  AaveV3PartialTakeProfitLambdaBase: enableAaveV3Automations,
  AaveV3PartialTakeProfitLambdaEthereum: enableAaveV3Automations,
  AaveV3PartialTakeProfitLambdaOptimism: enableAaveV3Automations,
  AaveV3Protection: true,
  AaveV3ProtectionLambdaArbitrum: enableAaveV3Automations,
  AaveV3ProtectionLambdaBase: enableAaveV3Automations,
  AaveV3ProtectionLambdaEthereum: enableAaveV3Automations,
  AaveV3ProtectionLambdaOptimism: enableAaveV3Automations,
  AaveV3ProtectionWrite: enableAaveV3Automations,
  AaveV3SafetySwitch: false,
  AaveV3SuppressValidation: false,
  AaveV3TrailingStopLossLambdaArbitrum: enableAaveV3Automations,
  AaveV3TrailingStopLossLambdaBase: enableAaveV3Automations,
  AaveV3TrailingStopLossLambdaEthereum: enableAaveV3Automations,
  AaveV3TrailingStopLossLambdaOptimism: enableAaveV3Automations,
  AjnaBase: true,
  AjnaPoolFinder: true,
  AjnaSafetySwitch: false,
  AjnaSuppressValidation: false,
  AnotherTestFeature: true, // used in unit tests
  BaseNetworkEnabled: true,
  ConstantMultipleReadOnly: false,
  DaiSavingsRate: true,
  DisableSidebarScroll: false,
  DsProxyMigrationArbitrum: true,
  DsProxyMigrationBase: true,
  DsProxyMigrationEthereum: true,
  DsProxyMigrationOptimism: true,
  EnableMigrations: true,
  EnableRefinance: true,
  Erc4626Vaults: true,
  Erc4626VaultsSafetySwitch: false,
  Erc4626VaultsSuppressValidation: false,
  FollowAAVEVaults: false,
  LambdaAutomations: {
    DisableNetValueCheck: notProduction,
    // same as AutomationFeatures enum in OB
    AaveV3: {
      autoBuy: enableAaveV3Automations,
      autoSell: enableAaveV3Automations,
      partialTakeProfit: enableAaveV3Automations,
      stopLoss: enableAaveV3Automations,
      trailingStopLoss: enableAaveV3Automations,
    },
    MorphoBlue: {
      autoBuy: true,
      autoSell: true,
      partialTakeProfit: true,
      stopLoss: true,
      trailingStopLoss: true,
    },
  },
  MakerTenderly: false,
  MorphoBlue: true,
  MorphoSafetySwitch: false,
  MorphoSuppressValidation: false,
  NewNavigation: true,
  NewPortfolio: true,
  Newsletter: true,
  OmniKitDebug: false,
  OmniPnlModal: false,
  ProductHubDebug: false,
  ProxyCreationDisabled: false,
  ProxyReveal: false,
  Rays: false,
  RaysDailyChallenge: false,
  ReadOnlyAutoTakeProfit: false,
  ReadOnlyBasicBS: false,
  Referrals: true,
  RefinanceSafetySwitch: false,
  RefinanceSuppressValidation: false,
  Sillyness: false,
  SkyUpgrade: true,
  SparkOptimization: false,
  SparkOptimizationEthereum: true,
  SparkPartialTakeProfitLambdaEthereum: true,
  SparkProtectionLambdaEthereum: true,
  SparkProtocolStopLoss: true,
  SparkSafetySwitch: false,
  SparkSuppressValidation: false,
  SparkTrailingStopLossLambdaEthereum: true,
  SparkWBTCDAI: true,
  StopLossOpenFlow: false,
  StopLossRead: true,
  StopLossWrite: true,
  TestFeature: false, // used in unit tests
  UseNetworkSwitcherForks: false,
  UseNetworkSwitcherTestnets: false,
  UseOmniKitLinks: false,
  UseRpcGateway: true,
});
