export const getFeatures = () => ({
  AaveV3ArbitrumBorrow: true,
  AaveV3ArbitrumEarn: false,
  AaveV3EarncbETHeth: false,
  AaveV3EarnrETHeth: false,
  AaveV3History: false,
  AaveV3OptimismBorrow: true,
  AaveV3OptimismEarn: false,
  AaveV3Protection: true,
  AaveV3ProtectionWrite: true,
  AjnaPoolFinder: true,
  AjnaSafetySwitch: true,
  AjnaSuppressValidation: false,
  MorphoSafetySwitch: false,
  MorphoSuppressValidation: false,
  AnotherTestFeature: true, // used in unit tests
  BaseNetworkEnabled: true,
  ConstantMultipleReadOnly: false,
  DaiSavingsRate: true,
  DisableSidebarScroll: false,
  FollowAAVEVaults: false,
  MorphoBlue: false,
  NewNavigation: true,
  ProxyCreationDisabled: false,
  ProxyReveal: false,
  ReadOnlyAutoTakeProfit: false,
  ReadOnlyBasicBS: false,
  Referrals: true,
  Sillyness: false,
  SparkProtocolStopLoss: true,
  StopLossOpenFlow: false,
  StopLossRead: true,
  StopLossWrite: true,
  TestFeature: false, // used in unit tests
  UseNetworkSwitcherForks: false,
  UseNetworkSwitcherTestnets: false,
  UseRpcGateway: true,
  NewPortfolio: true,
  MakerTenderly: false,
  SparkWBTCDAI: true,
});
