import {ADDRESSES, SystemKeys} from '@oasisdex/addresses'
import {IToken, Networks, TokenSymbols, tokens} from "🤝";

type TokenSubset = {
    [key in TokenSymbols]?: IToken;
};

type NetworkTokens = {
    [network in Networks]: TokenSubset[];
};

/**
 * Returns tokens for each network
 * Can be enhanced to return address enriched tokens for each network
 */
export const getTokensByNetwork = (): NetworkTokens => {
    const mainnetCommon = ADDRESSES[Networks.MAINNET][SystemKeys.COMMON]
    const optimismCommon = ADDRESSES[Networks.OPTIMISM][SystemKeys.COMMON]
    const arbitrumCommon = ADDRESSES[Networks.ARBITRUM][SystemKeys.COMMON]
    // const baseCommon = ADDRESSES[Networks.BASE][SystemKeys.COMMON]
    // const polygonCommon = ADDRESSES[Networks.POLYGON][SystemKeys.COMMON]
    const goerliCommon = ADDRESSES[Networks.GOERLI][SystemKeys.COMMON]
    // const optimismGoerliCommon = ADDRESSES[Networks.OPTIMISM_GOERLI][SystemKeys.COMMON]


    return {
        [Networks.MAINNET]: [
            {[TokenSymbols.USDC]: tokens.USDC.setAddress(mainnetCommon.USDC).toObject()},
            {[TokenSymbols.WETH]: tokens.WETH.setAddress(mainnetCommon.WETH).toObject()},
            {[TokenSymbols.STETH]: tokens.STETH.setAddress(mainnetCommon.STETH).toObject()},
            {[TokenSymbols.WSTETH]: tokens.WSTETH.setAddress(mainnetCommon.WSTETH).toObject()},
            {[TokenSymbols.WBTC]: tokens.WBTC.setAddress(mainnetCommon.WBTC).toObject()},
            {[TokenSymbols.DAI]: tokens.DAI.setAddress(mainnetCommon.DAI).toObject()},
            {[TokenSymbols.CBETH]: tokens.CBETH.setAddress(mainnetCommon.CBETH).toObject()},
            {[TokenSymbols.RETH]: tokens.RETH.setAddress(mainnetCommon.RETH).toObject()},
            {[TokenSymbols.AAVE]: tokens.AAVE.setAddress(mainnetCommon.AAVE).toObject()},
            {[TokenSymbols.LINK]: tokens.LINK.setAddress(mainnetCommon.LINK).toObject()},
            {[TokenSymbols.UNI]: tokens.UNI.setAddress(mainnetCommon.UNI).toObject()},
            // {[TokenSymbols.SUSHI]: tokens.SUSHI.setAddress(mainnetCommon.SUSHI).toObject()},
            // {[TokenSymbols.CRV]: tokens.CRV.setAddress(mainnetCommon.CRV).toObject()},
            // {[TokenSymbols.SNX]: tokens.SNX.setAddress(mainnetCommon.SNX).toObject()},
            {[TokenSymbols.ADAI]: tokens.ADAI.setAddress(mainnetCommon.ADAI).toObject()},
            {[TokenSymbols.BAL]: tokens.BAL.setAddress(mainnetCommon.BAL).toObject()},
            {[TokenSymbols.BAT]: tokens.BAT.setAddress(mainnetCommon.BAT).toObject()},
            {[TokenSymbols.COMP]: tokens.COMP.setAddress(mainnetCommon.COMP).toObject()},
            {[TokenSymbols.CRVV1ETHSTETH]: tokens.CRVV1ETHSTETH.setAddress(mainnetCommon.CRVV1ETHSTETH).toObject()},
            {[TokenSymbols.FRAX]: tokens.FRAX.setAddress(mainnetCommon.FRAX).toObject()},
            {[TokenSymbols.GHO]: tokens.GHO.setAddress(mainnetCommon.GHO).toObject()},
            {[TokenSymbols.GUNIV3DAIUSDC1]: tokens.GUNIV3DAIUSDC1.setAddress(mainnetCommon.GUNIV3DAIUSDC1).toObject()},
            {[TokenSymbols.GUNIV3DAIUSDC2]: tokens.GUNIV3DAIUSDC2.setAddress(mainnetCommon.GUNIV3DAIUSDC2).toObject()},
            {[TokenSymbols.GUSD]: tokens.GUSD.setAddress(mainnetCommon.GUSD).toObject()},
            {[TokenSymbols.KNC]: tokens.KNC.setAddress(mainnetCommon.KNC).toObject()},
            {[TokenSymbols.LDO]: tokens.LRC.setAddress(mainnetCommon.LDO).toObject()},
            {[TokenSymbols.LRC]: tokens.LRC.setAddress(mainnetCommon.LRC).toObject()},
            {[TokenSymbols.LUSD]: tokens.LUSD.setAddress(mainnetCommon.LUSD).toObject()},
            {[TokenSymbols.MANA]: tokens.MANA.setAddress(mainnetCommon.MANA).toObject()},
            {[TokenSymbols.MATIC]: tokens.MATIC.setAddress(mainnetCommon.MATIC).toObject()},
            {[TokenSymbols.PAX]: tokens.PAX.setAddress(mainnetCommon.PAX).toObject()},
            {[TokenSymbols.PAXUSD]: tokens.PAXUSD.setAddress(mainnetCommon.PAXUSD).toObject()},
            {[TokenSymbols.RENBTC]: tokens.RENBTC.setAddress(mainnetCommon.RENBTC).toObject()},
            {[TokenSymbols.RWA001]: tokens.RWA001.setAddress(mainnetCommon.RWA001).toObject()},
            {[TokenSymbols.RWA002]: tokens.RWA002.setAddress(mainnetCommon.RWA002).toObject()},
            {[TokenSymbols.RWA003]: tokens.RWA003.setAddress(mainnetCommon.RWA003).toObject()},
            {[TokenSymbols.RWA004]: tokens.RWA004.setAddress(mainnetCommon.RWA004).toObject()},
            {[TokenSymbols.RWA005]: tokens.RWA005.setAddress(mainnetCommon.RWA005).toObject()},
            {[TokenSymbols.RWA006]: tokens.RWA006.setAddress(mainnetCommon.RWA006).toObject()},
            {[TokenSymbols.SDAI]: tokens.SDAI.setAddress(mainnetCommon.SDAI).toObject()},
            {[TokenSymbols.TBTC]: tokens.TBTC.setAddress(mainnetCommon.TBTC).toObject()},
            {[TokenSymbols.TUSD]: tokens.TUSD.setAddress(mainnetCommon.TUSD).toObject()},
            {[TokenSymbols.UNIV2AAVEETH]: tokens.UNIV2AAVEETH.setAddress(mainnetCommon.UNIV2AAVEETH).toObject()},
            {[TokenSymbols.UNIV2DAIETH]: tokens.UNIV2DAIETH.setAddress(mainnetCommon.UNIV2DAIETH).toObject()},
            {[TokenSymbols.UNIV2DAIUSDC]: tokens.UNIV2DAIUSDC.setAddress(mainnetCommon.UNIV2DAIUSDC).toObject()},
            {[TokenSymbols.UNIV2DAIUSDT]: tokens.UNIV2DAIUSDT.setAddress(mainnetCommon.UNIV2DAIUSDT).toObject()},
            {[TokenSymbols.UNIV2ETHUSDT]: tokens.UNIV2ETHUSDT.setAddress(mainnetCommon.UNIV2ETHUSDT).toObject()},
            {[TokenSymbols.UNIV2LINKETH]: tokens.UNIV2LINKETH.setAddress(mainnetCommon.UNIV2LINKETH).toObject()},
            {[TokenSymbols.UNIV2UNIETH]: tokens.UNIV2UNIETH.setAddress(mainnetCommon.UNIV2UNIETH).toObject()},
            {[TokenSymbols.UNIV2USDCETH]: tokens.UNIV2USDCETH.setAddress(mainnetCommon.UNIV2USDCETH).toObject()},
            {[TokenSymbols.UNIV2WBTCDAI]: tokens.UNIV2WBTCDAI.setAddress(mainnetCommon.UNIV2WBTCDAI).toObject()},
            {[TokenSymbols.UNIV2WBTCETH]: tokens.UNIV2WBTCETH.setAddress(mainnetCommon.UNIV2WBTCETH).toObject()},
            {[TokenSymbols.USDT]: tokens.USDT.setAddress(mainnetCommon.USDT).toObject()},
            {[TokenSymbols.WLD]: tokens.WLD.setAddress(mainnetCommon.WLD).toObject()},
            {[TokenSymbols.YIELDBTC]: tokens.YIELDBTC.setAddress(mainnetCommon.YIELDBTC).toObject()},
            {[TokenSymbols.YIELDETH]: tokens.YIELDETH.setAddress(mainnetCommon.YIELDETH).toObject()},
            {[TokenSymbols.YFI]: tokens.YFI.setAddress(mainnetCommon.YFI).toObject()},
            {[TokenSymbols.ZRX]: tokens.ZRX.setAddress(mainnetCommon.ZRX).toObject()},
        ],
        [Networks.OPTIMISM]: [
            {[TokenSymbols.USDC]: tokens.USDC.setAddress(optimismCommon.USDC).toObject()},
            {[TokenSymbols.WETH]: tokens.WETH.setAddress(optimismCommon.WETH).toObject()},
            {[TokenSymbols.STETH]: tokens.STETH.setAddress(optimismCommon.STETH).toObject()},
            {[TokenSymbols.WSTETH]: tokens.WSTETH.setAddress(optimismCommon.WSTETH).toObject()},
            {[TokenSymbols.WBTC]: tokens.WBTC.setAddress(optimismCommon.WBTC).toObject()},
            {[TokenSymbols.DAI]: tokens.DAI.setAddress(optimismCommon.DAI).toObject()},
            {[TokenSymbols.CBETH]: tokens.CBETH.setAddress(optimismCommon.CBETH).toObject()},
            {[TokenSymbols.RETH]: tokens.RETH.setAddress(optimismCommon.RETH).toObject()},
            {[TokenSymbols.AAVE]: tokens.AAVE.setAddress(optimismCommon.AAVE).toObject()},
            {[TokenSymbols.LINK]: tokens.LINK.setAddress(optimismCommon.LINK).toObject()},
            {[TokenSymbols.UNI]: tokens.UNI.setAddress(optimismCommon.UNI).toObject()},
            // {[TokenSymbols.SUSHI]: tokens.SUSHI.setAddress(optimismCommon.SUSHI).toObject()},
            // {[TokenSymbols.CRV]: tokens.CRV.setAddress(optimismCommon.CRV).toObject()},
            // {[TokenSymbols.SNX]: tokens.SNX.setAddress(optimismCommon.SNX).toObject()},
            {[TokenSymbols.ADAI]: tokens.ADAI.setAddress(optimismCommon.ADAI).toObject()},
            {[TokenSymbols.BAL]: tokens.BAL.setAddress(optimismCommon.BAL).toObject()},
            {[TokenSymbols.BAT]: tokens.BAT.setAddress(optimismCommon.BAT).toObject()},
            {[TokenSymbols.COMP]: tokens.COMP.setAddress(optimismCommon.COMP).toObject()},
            {[TokenSymbols.CRVV1ETHSTETH]: tokens.CRVV1ETHSTETH.setAddress(optimismCommon.CRVV1ETHSTETH).toObject()},
            {[TokenSymbols.FRAX]: tokens.FRAX.setAddress(optimismCommon.FRAX).toObject()},
            {[TokenSymbols.GHO]: tokens.GHO.setAddress(optimismCommon.GHO).toObject()},
            {[TokenSymbols.GUNIV3DAIUSDC1]: tokens.GUNIV3DAIUSDC1.setAddress(optimismCommon.GUNIV3DAIUSDC1).toObject()},
            {[TokenSymbols.GUNIV3DAIUSDC2]: tokens.GUNIV3DAIUSDC2.setAddress(optimismCommon.GUNIV3DAIUSDC2).toObject()},
            {[TokenSymbols.GUSD]: tokens.GUSD.setAddress(optimismCommon.GUSD).toObject()},
            {[TokenSymbols.KNC]: tokens.KNC.setAddress(optimismCommon.KNC).toObject()},
            {[TokenSymbols.LDO]: tokens.LRC.setAddress(optimismCommon.LDO).toObject()},
            {[TokenSymbols.LRC]: tokens.LRC.setAddress(optimismCommon.LRC).toObject()},
            {[TokenSymbols.LUSD]: tokens.LUSD.setAddress(optimismCommon.LUSD).toObject()},
            {[TokenSymbols.MANA]: tokens.MANA.setAddress(optimismCommon.MANA).toObject()},
            {[TokenSymbols.MATIC]: tokens.MATIC.setAddress(optimismCommon.MATIC).toObject()},
            {[TokenSymbols.PAX]: tokens.PAX.setAddress(optimismCommon.PAX).toObject()},
            {[TokenSymbols.PAXUSD]: tokens.PAXUSD.setAddress(optimismCommon.PAXUSD).toObject()},
            {[TokenSymbols.RENBTC]: tokens.RENBTC.setAddress(optimismCommon.RENBTC).toObject()},
            {[TokenSymbols.RWA001]: tokens.RWA001.setAddress(optimismCommon.RWA001).toObject()},
            {[TokenSymbols.RWA002]: tokens.RWA002.setAddress(optimismCommon.RWA002).toObject()},
            {[TokenSymbols.RWA003]: tokens.RWA003.setAddress(optimismCommon.RWA003).toObject()},
            {[TokenSymbols.RWA004]: tokens.RWA004.setAddress(optimismCommon.RWA004).toObject()},
            {[TokenSymbols.RWA005]: tokens.RWA005.setAddress(optimismCommon.RWA005).toObject()},
            {[TokenSymbols.RWA006]: tokens.RWA006.setAddress(optimismCommon.RWA006).toObject()},
            {[TokenSymbols.SDAI]: tokens.SDAI.setAddress(optimismCommon.SDAI).toObject()},
            {[TokenSymbols.TBTC]: tokens.TBTC.setAddress(optimismCommon.TBTC).toObject()},
            {[TokenSymbols.TUSD]: tokens.TUSD.setAddress(optimismCommon.TUSD).toObject()},
            {[TokenSymbols.UNIV2AAVEETH]: tokens.UNIV2AAVEETH.setAddress(optimismCommon.UNIV2AAVEETH).toObject()},
            {[TokenSymbols.UNIV2DAIETH]: tokens.UNIV2DAIETH.setAddress(optimismCommon.UNIV2DAIETH).toObject()},
            {[TokenSymbols.UNIV2DAIUSDC]: tokens.UNIV2DAIUSDC.setAddress(optimismCommon.UNIV2DAIUSDC).toObject()},
            {[TokenSymbols.UNIV2DAIUSDT]: tokens.UNIV2DAIUSDT.setAddress(optimismCommon.UNIV2DAIUSDT).toObject()},
            {[TokenSymbols.UNIV2ETHUSDT]: tokens.UNIV2ETHUSDT.setAddress(optimismCommon.UNIV2ETHUSDT).toObject()},
            {[TokenSymbols.UNIV2LINKETH]: tokens.UNIV2LINKETH.setAddress(optimismCommon.UNIV2LINKETH).toObject()},
            {[TokenSymbols.UNIV2UNIETH]: tokens.UNIV2UNIETH.setAddress(optimismCommon.UNIV2UNIETH).toObject()},
            {[TokenSymbols.UNIV2USDCETH]: tokens.UNIV2USDCETH.setAddress(optimismCommon.UNIV2USDCETH).toObject()},
            {[TokenSymbols.UNIV2WBTCDAI]: tokens.UNIV2WBTCDAI.setAddress(optimismCommon.UNIV2WBTCDAI).toObject()},
            {[TokenSymbols.UNIV2WBTCETH]: tokens.UNIV2WBTCETH.setAddress(optimismCommon.UNIV2WBTCETH).toObject()},
            {[TokenSymbols.USDT]: tokens.USDT.setAddress(optimismCommon.USDT).toObject()},
            {[TokenSymbols.WLD]: tokens.WLD.setAddress(optimismCommon.WLD).toObject()},
            {[TokenSymbols.YIELDBTC]: tokens.YIELDBTC.setAddress(optimismCommon.YIELDBTC).toObject()},
            {[TokenSymbols.YIELDETH]: tokens.YIELDETH.setAddress(optimismCommon.YIELDETH).toObject()},
            {[TokenSymbols.YFI]: tokens.YFI.setAddress(optimismCommon.YFI).toObject()},
            {[TokenSymbols.ZRX]: tokens.ZRX.setAddress(optimismCommon.ZRX).toObject()},
        ],
        [Networks.ARBITRUM]: [
            {[TokenSymbols.USDC]: tokens.USDC.setAddress(arbitrumCommon.USDC).toObject()},
            {[TokenSymbols.WETH]: tokens.WETH.setAddress(arbitrumCommon.WETH).toObject()},
            {[TokenSymbols.STETH]: tokens.STETH.setAddress(arbitrumCommon.STETH).toObject()},
            {[TokenSymbols.WSTETH]: tokens.WSTETH.setAddress(arbitrumCommon.WSTETH).toObject()},
            {[TokenSymbols.WBTC]: tokens.WBTC.setAddress(arbitrumCommon.WBTC).toObject()},
            {[TokenSymbols.DAI]: tokens.DAI.setAddress(arbitrumCommon.DAI).toObject()},
            {[TokenSymbols.CBETH]: tokens.CBETH.setAddress(arbitrumCommon.CBETH).toObject()},
            {[TokenSymbols.RETH]: tokens.RETH.setAddress(arbitrumCommon.RETH).toObject()},
            {[TokenSymbols.AAVE]: tokens.AAVE.setAddress(arbitrumCommon.AAVE).toObject()},
            {[TokenSymbols.LINK]: tokens.LINK.setAddress(arbitrumCommon.LINK).toObject()},
            {[TokenSymbols.UNI]: tokens.UNI.setAddress(arbitrumCommon.UNI).toObject()},
            // {[TokenSymbols.SUSHI]: tokens.SUSHI.setAddress(arbitrumCommon.SUSHI).toObject()},
            // {[TokenSymbols.CRV]: tokens.CRV.setAddress(arbitrumCommon.CRV).toObject()},
            // {[TokenSymbols.SNX]: tokens.SNX.setAddress(arbitrumCommon.SNX).toObject()},
            {[TokenSymbols.ADAI]: tokens.ADAI.setAddress(arbitrumCommon.ADAI).toObject()},
            {[TokenSymbols.BAL]: tokens.BAL.setAddress(arbitrumCommon.BAL).toObject()},
            {[TokenSymbols.BAT]: tokens.BAT.setAddress(arbitrumCommon.BAT).toObject()},
            {[TokenSymbols.COMP]: tokens.COMP.setAddress(arbitrumCommon.COMP).toObject()},
            {[TokenSymbols.CRVV1ETHSTETH]: tokens.CRVV1ETHSTETH.setAddress(arbitrumCommon.CRVV1ETHSTETH).toObject()},
            {[TokenSymbols.FRAX]: tokens.FRAX.setAddress(arbitrumCommon.FRAX).toObject()},
            {[TokenSymbols.GHO]: tokens.GHO.setAddress(arbitrumCommon.GHO).toObject()},
            {[TokenSymbols.GUNIV3DAIUSDC1]: tokens.GUNIV3DAIUSDC1.setAddress(arbitrumCommon.GUNIV3DAIUSDC1).toObject()},
            {[TokenSymbols.GUNIV3DAIUSDC2]: tokens.GUNIV3DAIUSDC2.setAddress(arbitrumCommon.GUNIV3DAIUSDC2).toObject()},
            {[TokenSymbols.GUSD]: tokens.GUSD.setAddress(arbitrumCommon.GUSD).toObject()},
            {[TokenSymbols.KNC]: tokens.KNC.setAddress(arbitrumCommon.KNC).toObject()},
            {[TokenSymbols.LDO]: tokens.LRC.setAddress(arbitrumCommon.LDO).toObject()},
            {[TokenSymbols.LRC]: tokens.LRC.setAddress(arbitrumCommon.LRC).toObject()},
            {[TokenSymbols.LUSD]: tokens.LUSD.setAddress(arbitrumCommon.LUSD).toObject()},
            {[TokenSymbols.MANA]: tokens.MANA.setAddress(arbitrumCommon.MANA).toObject()},
            {[TokenSymbols.MATIC]: tokens.MATIC.setAddress(arbitrumCommon.MATIC).toObject()},
            {[TokenSymbols.PAX]: tokens.PAX.setAddress(arbitrumCommon.PAX).toObject()},
            {[TokenSymbols.PAXUSD]: tokens.PAXUSD.setAddress(arbitrumCommon.PAXUSD).toObject()},
            {[TokenSymbols.RENBTC]: tokens.RENBTC.setAddress(arbitrumCommon.RENBTC).toObject()},
            {[TokenSymbols.RWA001]: tokens.RWA001.setAddress(arbitrumCommon.RWA001).toObject()},
            {[TokenSymbols.RWA002]: tokens.RWA002.setAddress(arbitrumCommon.RWA002).toObject()},
            {[TokenSymbols.RWA003]: tokens.RWA003.setAddress(arbitrumCommon.RWA003).toObject()},
            {[TokenSymbols.RWA004]: tokens.RWA004.setAddress(arbitrumCommon.RWA004).toObject()},
            {[TokenSymbols.RWA005]: tokens.RWA005.setAddress(arbitrumCommon.RWA005).toObject()},
            {[TokenSymbols.RWA006]: tokens.RWA006.setAddress(arbitrumCommon.RWA006).toObject()},
            {[TokenSymbols.SDAI]: tokens.SDAI.setAddress(arbitrumCommon.SDAI).toObject()},
            {[TokenSymbols.TBTC]: tokens.TBTC.setAddress(arbitrumCommon.TBTC).toObject()},
            {[TokenSymbols.TUSD]: tokens.TUSD.setAddress(arbitrumCommon.TUSD).toObject()},
            {[TokenSymbols.UNIV2AAVEETH]: tokens.UNIV2AAVEETH.setAddress(arbitrumCommon.UNIV2AAVEETH).toObject()},
            {[TokenSymbols.UNIV2DAIETH]: tokens.UNIV2DAIETH.setAddress(arbitrumCommon.UNIV2DAIETH).toObject()},
            {[TokenSymbols.UNIV2DAIUSDC]: tokens.UNIV2DAIUSDC.setAddress(arbitrumCommon.UNIV2DAIUSDC).toObject()},
            {[TokenSymbols.UNIV2DAIUSDT]: tokens.UNIV2DAIUSDT.setAddress(arbitrumCommon.UNIV2DAIUSDT).toObject()},
            {[TokenSymbols.UNIV2ETHUSDT]: tokens.UNIV2ETHUSDT.setAddress(arbitrumCommon.UNIV2ETHUSDT).toObject()},
            {[TokenSymbols.UNIV2LINKETH]: tokens.UNIV2LINKETH.setAddress(arbitrumCommon.UNIV2LINKETH).toObject()},
            {[TokenSymbols.UNIV2UNIETH]: tokens.UNIV2UNIETH.setAddress(arbitrumCommon.UNIV2UNIETH).toObject()},
            {[TokenSymbols.UNIV2USDCETH]: tokens.UNIV2USDCETH.setAddress(arbitrumCommon.UNIV2USDCETH).toObject()},
            {[TokenSymbols.UNIV2WBTCDAI]: tokens.UNIV2WBTCDAI.setAddress(arbitrumCommon.UNIV2WBTCDAI).toObject()},
            {[TokenSymbols.UNIV2WBTCETH]: tokens.UNIV2WBTCETH.setAddress(arbitrumCommon.UNIV2WBTCETH).toObject()},
            {[TokenSymbols.USDT]: tokens.USDT.setAddress(arbitrumCommon.USDT).toObject()},
            {[TokenSymbols.WLD]: tokens.WLD.setAddress(arbitrumCommon.WLD).toObject()},
            {[TokenSymbols.YIELDBTC]: tokens.YIELDBTC.setAddress(arbitrumCommon.YIELDBTC).toObject()},
            {[TokenSymbols.YIELDETH]: tokens.YIELDETH.setAddress(arbitrumCommon.YIELDETH).toObject()},
            {[TokenSymbols.YFI]: tokens.YFI.setAddress(arbitrumCommon.YFI).toObject()},
            {[TokenSymbols.ZRX]: tokens.ZRX.setAddress(arbitrumCommon.ZRX).toObject()},
        ],
        [Networks.BASE]: [],
        [Networks.POLYGON]: [],
        [Networks.GOERLI]: [
            {[TokenSymbols.USDC]: tokens.USDC.setAddress(goerliCommon.USDC).toObject()},
            {[TokenSymbols.WETH]: tokens.WETH.setAddress(goerliCommon.WETH).toObject()},
            {[TokenSymbols.STETH]: tokens.STETH.setAddress(goerliCommon.STETH).toObject()},
            {[TokenSymbols.WSTETH]: tokens.WSTETH.setAddress(goerliCommon.WSTETH).toObject()},
            {[TokenSymbols.WBTC]: tokens.WBTC.setAddress(goerliCommon.WBTC).toObject()},
            {[TokenSymbols.DAI]: tokens.DAI.setAddress(goerliCommon.DAI).toObject()},
            {[TokenSymbols.CBETH]: tokens.CBETH.setAddress(goerliCommon.CBETH).toObject()},
            {[TokenSymbols.RETH]: tokens.RETH.setAddress(goerliCommon.RETH).toObject()},
            {[TokenSymbols.AAVE]: tokens.AAVE.setAddress(goerliCommon.AAVE).toObject()},
            {[TokenSymbols.LINK]: tokens.LINK.setAddress(goerliCommon.LINK).toObject()},
            {[TokenSymbols.UNI]: tokens.UNI.setAddress(goerliCommon.UNI).toObject()},
            // {[TokenSymbols.SUSHI]: tokens.SUSHI.setAddress(goerliCommon.SUSHI).toObject()},
            // {[TokenSymbols.CRV]: tokens.CRV.setAddress(goerliCommon.CRV).toObject()},
            // {[TokenSymbols.SNX]: tokens.SNX.setAddress(goerliCommon.SNX).toObject()},
            {[TokenSymbols.ADAI]: tokens.ADAI.setAddress(goerliCommon.ADAI).toObject()},
            {[TokenSymbols.BAL]: tokens.BAL.setAddress(goerliCommon.BAL).toObject()},
            {[TokenSymbols.BAT]: tokens.BAT.setAddress(goerliCommon.BAT).toObject()},
            {[TokenSymbols.COMP]: tokens.COMP.setAddress(goerliCommon.COMP).toObject()},
            {[TokenSymbols.CRVV1ETHSTETH]: tokens.CRVV1ETHSTETH.setAddress(goerliCommon.CRVV1ETHSTETH).toObject()},
            {[TokenSymbols.FRAX]: tokens.FRAX.setAddress(goerliCommon.FRAX).toObject()},
            {[TokenSymbols.GHO]: tokens.GHO.setAddress(goerliCommon.GHO).toObject()},
            {[TokenSymbols.GUNIV3DAIUSDC1]: tokens.GUNIV3DAIUSDC1.setAddress(goerliCommon.GUNIV3DAIUSDC1).toObject()},
            {[TokenSymbols.GUNIV3DAIUSDC2]: tokens.GUNIV3DAIUSDC2.setAddress(goerliCommon.GUNIV3DAIUSDC2).toObject()},
            {[TokenSymbols.GUSD]: tokens.GUSD.setAddress(goerliCommon.GUSD).toObject()},
            {[TokenSymbols.KNC]: tokens.KNC.setAddress(goerliCommon.KNC).toObject()},
            {[TokenSymbols.LDO]: tokens.LRC.setAddress(goerliCommon.LDO).toObject()},
            {[TokenSymbols.LRC]: tokens.LRC.setAddress(goerliCommon.LRC).toObject()},
            {[TokenSymbols.LUSD]: tokens.LUSD.setAddress(goerliCommon.LUSD).toObject()},
            {[TokenSymbols.MANA]: tokens.MANA.setAddress(goerliCommon.MANA).toObject()},
            {[TokenSymbols.MATIC]: tokens.MATIC.setAddress(goerliCommon.MATIC).toObject()},
            {[TokenSymbols.PAX]: tokens.PAX.setAddress(goerliCommon.PAX).toObject()},
            {[TokenSymbols.PAXUSD]: tokens.PAXUSD.setAddress(goerliCommon.PAXUSD).toObject()},
            {[TokenSymbols.RENBTC]: tokens.RENBTC.setAddress(goerliCommon.RENBTC).toObject()},
            {[TokenSymbols.RWA001]: tokens.RWA001.setAddress(goerliCommon.RWA001).toObject()},
            {[TokenSymbols.RWA002]: tokens.RWA002.setAddress(goerliCommon.RWA002).toObject()},
            {[TokenSymbols.RWA003]: tokens.RWA003.setAddress(goerliCommon.RWA003).toObject()},
            {[TokenSymbols.RWA004]: tokens.RWA004.setAddress(goerliCommon.RWA004).toObject()},
            {[TokenSymbols.RWA005]: tokens.RWA005.setAddress(goerliCommon.RWA005).toObject()},
            {[TokenSymbols.RWA006]: tokens.RWA006.setAddress(goerliCommon.RWA006).toObject()},
            {[TokenSymbols.SDAI]: tokens.SDAI.setAddress(goerliCommon.SDAI).toObject()},
            {[TokenSymbols.TBTC]: tokens.TBTC.setAddress(goerliCommon.TBTC).toObject()},
            {[TokenSymbols.TUSD]: tokens.TUSD.setAddress(goerliCommon.TUSD).toObject()},
            {[TokenSymbols.UNIV2AAVEETH]: tokens.UNIV2AAVEETH.setAddress(goerliCommon.UNIV2AAVEETH).toObject()},
            {[TokenSymbols.UNIV2DAIETH]: tokens.UNIV2DAIETH.setAddress(goerliCommon.UNIV2DAIETH).toObject()},
            {[TokenSymbols.UNIV2DAIUSDC]: tokens.UNIV2DAIUSDC.setAddress(goerliCommon.UNIV2DAIUSDC).toObject()},
            {[TokenSymbols.UNIV2DAIUSDT]: tokens.UNIV2DAIUSDT.setAddress(goerliCommon.UNIV2DAIUSDT).toObject()},
            {[TokenSymbols.UNIV2ETHUSDT]: tokens.UNIV2ETHUSDT.setAddress(goerliCommon.UNIV2ETHUSDT).toObject()},
            {[TokenSymbols.UNIV2LINKETH]: tokens.UNIV2LINKETH.setAddress(goerliCommon.UNIV2LINKETH).toObject()},
            {[TokenSymbols.UNIV2UNIETH]: tokens.UNIV2UNIETH.setAddress(goerliCommon.UNIV2UNIETH).toObject()},
            {[TokenSymbols.UNIV2USDCETH]: tokens.UNIV2USDCETH.setAddress(goerliCommon.UNIV2USDCETH).toObject()},
            {[TokenSymbols.UNIV2WBTCDAI]: tokens.UNIV2WBTCDAI.setAddress(goerliCommon.UNIV2WBTCDAI).toObject()},
            {[TokenSymbols.UNIV2WBTCETH]: tokens.UNIV2WBTCETH.setAddress(goerliCommon.UNIV2WBTCETH).toObject()},
            {[TokenSymbols.USDT]: tokens.USDT.setAddress(goerliCommon.USDT).toObject()},
            {[TokenSymbols.WLD]: tokens.WLD.setAddress(goerliCommon.WLD).toObject()},
            {[TokenSymbols.YIELDBTC]: tokens.YIELDBTC.setAddress(goerliCommon.YIELDBTC).toObject()},
            {[TokenSymbols.YIELDETH]: tokens.YIELDETH.setAddress(goerliCommon.YIELDETH).toObject()},
            {[TokenSymbols.YFI]: tokens.YFI.setAddress(goerliCommon.YFI).toObject()},
            {[TokenSymbols.ZRX]: tokens.ZRX.setAddress(goerliCommon.ZRX).toObject()},
        ],
        [Networks.OPTIMISM_GOERLI]: [],
        [Networks.ARBITRUM_GOERLI]: [],
        [Networks.POLYGON_MUMBAI]: [],
    }
};