export enum DenominationSymbols {
    USD = 'USD',
    ETH = 'ETH',
    BTC = 'BTC',
    GBP = 'GBP',
    EUR = 'EUR',
    JPY = 'JPY',
    KRW = 'KRW',
    CNY = 'CNY',
    AUD = 'AUD',
    CAD = 'CAD',
    CHF = 'CHF',
    ARS = 'ARS',
    PHP = 'PHP',
    NZD = 'NZD',
    SGD = 'SGD',
    NGN = 'NGN',
    ZAR = 'ZAR',
    RUB = 'RUB',
    INR = 'INR',
    BRL = 'BRL'
}
