/**
 * Enum representing various token symbols supported by the platform.
 * This provides a standardized way to reference these tokens throughout the application.
 */
export enum TokenSymbol {
  ETH = 'ETH', // Ethereum
  WETH = 'WETH', // Wrapped Ethereum
  WEETH = 'WEETH', // Wrapped Ethereum
  STETH = 'STETH', // stakedETH
  WSTETH = 'WSTETH', // Wrapped stakedETH
  WBTC = 'WBTC', // Wrapped Bitcoin
  USDC = 'USDC', // USD Coin
  USDBC = 'USDBC', // USD Coin BSC
  USDCE = 'USDCE', // USD Coin (Bridged)
  DAI = 'DAI', // Dai Stablecoin
  CBETH = 'CBETH', // Compound ETH (assuming, provide accurate description if different)
  CBBTC = 'CBBTC', // Coinbase BTC
  RETH = 'RETH', // Rocket Pool ETH
  AAVE = 'AAVE',
  LINK = 'LINK',
  UNI = 'UNI',
  SUSHI = 'SUSHI',
  CRV = 'CRV',
  SNX = 'SNX',
  ADAI = 'ADAI', // Aave interest bearing DAI
  BAL = 'BAL',
  BAT = 'BAT',
  COMP = 'COMP',
  CRVV1ETHSTETH = 'CRVV1ETHSTETH', // Specific Curve pool token
  FRAX = 'FRAX',
  GHO = 'GHO',
  GNO = 'GNO',
  GUNIV3DAIUSDC1 = 'GUNIV3DAIUSDC1', // Gelato Uniswap V3 DAI-USDC pool token variant 1
  GUNIV3DAIUSDC2 = 'GUNIV3DAIUSDC2', // Gelato Uniswap V3 DAI-USDC pool token variant 2
  GUSD = 'GUSD', // Gemini Dollar
  KNC = 'KNC', // Kyber Network Crystal
  LDO = 'LDO', // Lido DAO Token
  LRC = 'LRC', // Loopring
  LUSD = 'LUSD', // Liquity USD Stablecoin
  MANA = 'MANA', // Decentraland
  MATIC = 'MATIC', // Polygon token (previously Matic)
  MKR = 'MKR', // Maker
  PAX = 'PAX', // Paxos Standard
  PAXUSD = 'PAXUSD', // Paxos Standard Dollar
  RENBTC = 'RENBTC', // Ren Bitcoin
  RWA001 = 'RWA001', // Real-World Asset 001 (Maker)
  RWA002 = 'RWA002',
  RWA003 = 'RWA003',
  RWA004 = 'RWA004',
  RWA005 = 'RWA005',
  RWA006 = 'RWA006',
  SDAI = 'SDAI', // Some specific version of DAI
  TBTC = 'TBTC', // tBTC (tokenised Bitcoin on Ethereum)
  TUSD = 'TUSD', // TrueUSD
  UNIV2AAVEETH = 'UNIV2AAVEETH', // Uniswap V2 AAVE-ETH Liquidity Pool Token
  UNIV2DAIETH = 'UNIV2DAIETH', // Uniswap V2 DAI-ETH Liquidity Pool Token
  UNIV2DAIUSDC = 'UNIV2DAIUSDC',
  UNIV2DAIUSDT = 'UNIV2DAIUSDT',
  UNIV2ETHUSDT = 'UNIV2ETHUSDT',
  UNIV2LINKETH = 'UNIV2LINKETH',
  UNIV2UNIETH = 'UNIV2UNIETH',
  UNIV2USDCETH = 'UNIV2USDCETH',
  UNIV2WBTCDAI = 'UNIV2WBTCDAI',
  UNIV2WBTCETH = 'UNIV2WBTCETH',
  USDT = 'USDT', // Tether
  WLD = 'WLD',
  YIELDBTC = 'YIELDBTC', // Yield instrument for BTC
  YIELDETH = 'YIELDETH', // Yield instrument for ETH
  YFI = 'YFI', // yearn.finance
  ZRX = 'ZRX', // 0x
}
